version: '2'
services:
  mrxavierjhipster-app:
    image: mrxavierjhipster
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://mrxavierjhipster-mysql:3306/mrxavierjhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  mrxavierjhipster-mysql:
    extends:
      file: mysql.yml
      service: mrxavierjhipster-mysql
